import fs from "fs/promises";
import path from "path";
import yaml from "js-yaml";
import { execFile } from "child_process";
import { promisify } from "util";

const execAsync = promisify(execFile);

// Scan tools/<name>/tool.json and regenerate docker-compose.tools.yml.
export async function updateCompose(workspace) {
  const toolsDir = path.join(workspace, "tools");
  const composePath = path.join(workspace, "docker-compose.tools.yml");

  let toolDirs = [];
  try {
    const entries = await fs.readdir(toolsDir, { withFileTypes: true });
    toolDirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  } catch {
    console.log("[compose-manager] No tools directory found");
  }

  const services = {};

  for (const toolDir of toolDirs) {
    const manifestPath = path.join(toolsDir, toolDir, "tool.json");
    let manifest;

    try {
      const raw = await fs.readFile(manifestPath, "utf8");
      manifest = JSON.parse(raw);
    } catch {
      continue;
    }

    const serviceName = `tool-${toolDir}`;
    const imageName = `cosi-tool-${toolDir}:latest`;

    const environment = [];

    // Add secret environment variables
    for (const secret of manifest.secrets || []) {
      const envKey = secret
        .replace(/\//g, "_")
        .replace(/-/g, "_")
        .toUpperCase();
      const envVarName = `COSI_SECRET_${envKey}`;
      environment.push(`${envVarName}=\${${envVarName}:-}`);
    }

    services[serviceName] = {
      image: imageName,
      container_name: `cosi-${serviceName}`,
      networks: ["cosi-network"],
      restart: "unless-stopped",
      ...(environment.length > 0 ? { environment } : {}),
    };
  }

  const composeData = {
    services,
    networks: {
      "cosi-network": {
        external: true,
        name: "cosi_cosi-network",
      },
    },
  };

  const header = "# Auto-generated by cosi-builder — do not edit manually\n";
  const yamlContent = yaml.dump(composeData, { lineWidth: -1 });
  await fs.writeFile(composePath, header + yamlContent, "utf8");

  console.log(
    `[compose-manager] Updated docker-compose.tools.yml with ${Object.keys(services).length} tool(s)`
  );

  // Bring up new/changed services
  if (Object.keys(services).length > 0) {
    try {
      const secretsFile = path.join(workspace, "secrets.env");
      const hasSecrets = await fs.access(secretsFile).then(() => true).catch(() => false);

      await execAsync("docker", [
        "compose", "-p", "cosi",
        "-f", composePath,
        ...(hasSecrets ? ["--env-file", secretsFile] : []),
        "up", "-d", "--no-deps",
      ]);
      console.log("[compose-manager] docker compose up -d completed");
    } catch (err) {
      console.error("[compose-manager] docker compose up failed:", err.message);
    }
  }
}
